/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package makepatch;

import com.melody.JettLog;
import com.melody.util.Util;
import org.junit.Test;

public class AppTest {
    @Test public void checksumTest() {

        long start = System.currentTimeMillis();

        String[] args = new String[3];
        args[1] = "./assets/source.apk";
        args[2] = "./assets/target.apk";


        for (int k=0;k<10000000;k++)
        {
            csc32Test();
        }



        System.out.print("time consume:"+(System.currentTimeMillis() - start));
    }

    private static void csc32Test()
    {
        int SIZE = 8;

        byte[] bytes = new byte[SIZE];
        for (int i = 0; i<SIZE; i++)
        {
            bytes[i] = (byte)i;
        }

        Util.getCRC32Checksum(bytes, 0, bytes.length);
//        JettLog.d("test", "checksum1:"+Util.getCRC32Checksum(bytes, 0, bytes.length));

        for (int i = 0; i<SIZE; i++)
        {
            bytes[SIZE-1-i] = (byte)(i);
        }
        Util.getCRC32Checksum(bytes, 0, bytes.length);
//        JettLog.d("test", "checksum2:"+Util.getCRC32Checksum(bytes, 0, bytes.length));
    }

    private static void checkSumTest()
    {
        int SIZE = 8;

        byte[] bytes = new byte[SIZE];
        for (int i = 0; i<SIZE; i++)
        {
            bytes[i] = (byte)i;
        }

        Util.getChecksum(bytes, 0, bytes.length);
//        JettLog.d("test", "checksum1:"+Util.getCRC32Checksum(bytes, 0, bytes.length));

        for (int i = 0; i<SIZE; i++)
        {
            bytes[SIZE-1-i] = (byte)(i);
        }
        Util.getChecksum(bytes, 0, bytes.length);
//        JettLog.d("test", "checksum2:"+Util.getCRC32Checksum(bytes, 0, bytes.length));
    }
}
